<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de errores</title>
</head>
<body>
    <h1>Manejo de Errores</h1>
    <script>
        /*try {
            console.log("En el Try se agrega el código a evaluar");
            noExiste;
            //console.log("Segundo mensaje en el try");
            } catch (error) {
                console.log("Catch, captura cualquier error surgido o lanzado en el try");
                console.log(error);
            } finally {
                console.log("El bloque finally se ejecutará siempre al final de unbloque try-catch");
        }*/

        try {
            let numero = 50; //"hola";
            if (isNaN(numero)) {//funcion isNaN devuelve true o false si el valor es un numero
                throw new Error("El caractér introducido no es un Número");
            }// si es verdadero se ejecuta la operacion
            console.log(numero * numero);
            } catch (error) {
            console.log(`Se produjo el siguiente error: ${error}`);
        }

    </script>
</body>
</html>